# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Ferdinand Rivera Morell 2015-2021.

trigger:
  branches:
    include:
    - main
    - release
    - feature/*
    - version/*
  paths:
    exclude:
    - .circleci/*
    - .cirrus.yml
    - .drone.star
    - .github/workflows/*
    - .semaphore/*
    - .travis.yml
    - appveyor.yml
    - README.*
pr:
  branches:
    include:
    - main
    - version/*
  paths:
    exclude:
    - appveyor.yml

variables:
- { name: linux_latest_vm, value: 'ubuntu-22.04' }
- { name: windows_latest_vm, value: 'windows-2022' }
- { name: clang_latest, value: '18' }
- { name: clang_latest_libstdcxx, value: 9 }
- { name: gcc_latest, value: '13' }
- { name: vc_latest, value: 'vc143' }
- { name: vs_latest, value: '2022' }
- { name: xc_latest, value: '15.0.1' }
- { name: macos_latest_vm, value: 'macOS-13' }

resources:
  containers:
    - { container: gcc_latest, image: 'gcc:latest', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: clang_latest, image: 'chainguard/clang:latest', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: ubuntu_2404, image: 'ubuntu:24.04', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: ubuntu_2204, image: 'ubuntu:22.04', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: ubuntu_2004, image: 'ubuntu:20.04', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: ubuntu_1804, image: 'ubuntu:18.04', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: ubuntu_1604, image: 'ubuntu:16.04', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: debian_testing, image: 'debian:testing', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: debian_12, image: 'debian:12', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: debian_11, image: 'debian:11', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: debian_10, image: 'debian:10', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: debian_9, image: 'debian/eol:stretch', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }
    - { container: debian_8, image: 'debian/eol:jessie', options: '--name container -v /usr/bin/docker:/tmp/docker:ro' }

stages:

- stage: Compilers
  dependsOn:
  jobs:

  - job: Linux
    strategy:
      matrix:
        GCC 13 - Ubuntu 24.04 : { PACKAGES: build-essential, CONTAINER: "ubuntu:24.04" }
        GCC 12 - Debian 12    : { PACKAGES: build-essential, CONTAINER: "debian:12" }
        GCC 11 - Ubuntu 22.04 : { PACKAGES: build-essential, CONTAINER: "ubuntu:22.04" }
        GCC 10 - Debian 11    : { PACKAGES: build-essential, CONTAINER: "debian:11" }
        GCC 9  - Ubuntu 20.04 : { PACKAGES: build-essential, CONTAINER: "ubuntu:20.04" }
        GCC 8  - Debian 10    : { PACKAGES: build-essential, CONTAINER: "debian:10" }
        GCC 7  - Ubuntu 18.04 : { PACKAGES: build-essential, CONTAINER: "ubuntu:18.04" }
        GCC 6  - Debian 9     : { PACKAGES: build-essential, CONTAINER: "debian/eol:stretch" }
        GCC 5  - Ubuntu 16.04 : { PACKAGES: build-essential, CONTAINER: "ubuntu:16.04" }
        GCC 4.9 - Debian 8    : { PACKAGES: build-essential, CONTAINER: "debian/eol:jessie" }

        Clang 18 - Ubuntu 24.04 : { PACKAGES: clang, CONTAINER: "ubuntu:24.04" }
        Clang 14 - Debian 12    : { PACKAGES: clang, CONTAINER: "debian:12" }
        Clang 14 - Ubuntu 22.04 : { PACKAGES: clang, CONTAINER: "ubuntu:22.04" }
        Clang 11 - Debian 11    : { PACKAGES: clang, CONTAINER: "debian:11" }
        Clang 10 - Ubuntu 20.04 : { PACKAGES: clang, CONTAINER: "ubuntu:20.04" }
        Clang 7  - Debian 10    : { PACKAGES: clang, CONTAINER: "debian:10" }
        Clang 6  - Ubuntu 18.04 : { PACKAGES: clang, CONTAINER: "ubuntu:18.04" }
        Clang 3.8 - Debian 9    : { PACKAGES: clang, CONTAINER: "debian/eol:stretch" }
        Clang 3.8 - Ubuntu 16.04: { PACKAGES: clang, CONTAINER: "ubuntu:16.04" }
        Clang 3.5 - Debian 8    : { PACKAGES: clang, CONTAINER: "debian/eol:jessie" }
    pool:
      vmImage: ubuntu-latest
    container:
      image: $[ variables['CONTAINER'] ]
      options: --name container
    steps:
    - script: whoami
    - template: .ci/azp-linux-prep-container.yml
    - template: .ci/azp-linux-test.yml
